CREATE TABLE audit_logs (
    id SERIAL PRIMARY KEY,
    action VARCHAR(50) NOT NULL CHECK (action IN ('UPLOAD', 'ACCESS_REQUESTED', 'ACCESS_GRANTED', 'ACCESS_REVOKED', 'FILE_ACCESSED', 'ACCESS_DENIED', 'INTEGRITY_VERIFIED', 'INTEGRITY_FAILED', 'LOGIN', 'LOGOUT')),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details TEXT
);